# Generated by Django 2.0.2 on 2019-07-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190721_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='src',
            field=models.TextField(default=''),
        ),
    ]
